#pragma once

#include "CorE/version.hpp"

#define CORENGINE_BUILDTYPE_LINUX_WAYLAND 1
#define CORENGINE_BUILDTYPE_LINUX_XLIB 2
#define CORENGINE_BUILDTYPE_APPLE_METAL 1
#define CORENGINE_BUILDTYPE_APPLE_MACOS 2
#define CORENGINE_BUILDTYPE_APPLE_IOS 3

#define CORENGINE_UNDEFINED 0

#define CORENGINE_ANDROID 1
#define CORENGINE_LINUX_WAYLAND 2
#define CORENGINE_LINUX_XLIB 3
#define CORENGINE_WINDOWS 4
#define CORENGINE_APPLE_METAL 5
#define CORENGINE_APPLE_MACOS 6
#define CORENGINE_APPLE_IOS 7

#ifdef CORENGINE_BUILDFOR_ANDROID
#define VK_USE_PLATFORM_ANDROID_KHR
#define CORENGINE_PLATFORM CORENGINE_ANDROID
#elif defined CORENGINE_BUILDFOR_LINUX && CORENGINE_BUILDFOR_LINUX == CORENGINE_BUILDTYPE_LINUX_WAYLAND
#define VK_USE_PLATFORM_WAYLAND_KHR
#define CORENGINE_PLATFORM CORENGINE_LINUX_WAYLAND
#elif defined CORENGINE_BUILDFOR_LINUX && CORENGINE_BUILDFOR_LINUX == CORENGINE_BUILDTYPE_LINUX_XLIB
#define VK_USE_PLATFORM_XLIB_KHR
#define CORENGINE_PLATFORM CORENGINE_LINUX_XLIB

#elif defined CORENGINE_BUILDFOR_WINDOWS
#define VK_USE_PLATFORM_WIN32_KHR
#define CORENGINE_PLATFORM CORENGINE_WINDOWS

#elif defined CORENGINE_BUILDFOR_APPLE && CORENGINE_BUILDFOR_APPLE == CORENGINE_BUILDTYPE_APPLE_METAL
#define VK_USE_PLATFORM_METAL_EXT
#define CORENGINE_PLATFORM CORENGINE_APPLE_METAL
#elif defined CORENGINE_BUILDFOR_APPLE && CORENGINE_BUILDFOR_APPLE == CORENGINE_BUILDTYPE_APPLE_MACOS
#define VK_USE_PLATFORM_MACOS_MVK
#define CORENGINE_PLATFORM CORENGINE_APPLE_MACOS
#elif defined CORENGINE_BUILDFOR_APPLE && CORENGINE_BUILDFOR_APPLE == CORENGINE_BUILDTYPE_APPLE_IOS
#define VK_USE_PLATFORM_IOS_MVK
#define CORENGINE_PLATFORM CORENGINE_APPLE_IOS

#else
#define CORENGINE_PLATFORM CORENGINE_UNDEFINED

#endif

#include <vulkan/vulkan.hpp>